VideoHosting.Web/Controllers/VideosController.cs
using System.Web.Mvc;

namespace VideoHosting.Web.Controllers
{
    public class VideosController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Watch(int videoId)
        {
            ViewBag.VideoId = videoId;
            return View();
        }
	}
}

VideoHosting.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand w-100" href="/">
            <img src="~/Content/Images/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            Plays video with me!
        </a>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VideoHosting</p>
        </footer>
    </div>
    <script type="text/javascript">
        var urlGetAllVideos = '@Url.HttpRouteUrl("GetAllVideo", new {})';
        var urlAddVideo = '@Url.HttpRouteUrl("AddVideo", new {})';
        var urlUploadVideo = '@Url.HttpRouteUrl("UploadFile", new {})';
        var urlPlayVideo = '@Url.HttpRouteUrl("PlayVideo", new {})';
        var urlWatchVideo = '@Url.Action("Watch","Videos")'; 
    </script>
</body>
</html>